repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks: 
      - id: ruff
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*
          )$
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks: 
      - id: black
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*
          )$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks: 
      - id: mypy
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*|
              libs/.*
          )$ 