repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*|
              model_testing/.*
          )$
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*|
              model_testing/.*
          )$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
        exclude: |
          (?x)^(
              \.archive/.*|
              apps/.*|
              intake/.*|
              \.consult/.*|
              \.cursor/project_intelligence_cache/.*|
              libs/.*|
              model_testing/.*
          )$
  - repo: local
    hooks:
      - id: forbid-j2-in-libs
        name: Forbid .j2 references in libs
        entry: bash
        args:
          - -c
          - >-
            if grep -R --line-number -E '\\.j2' libs; then
            echo 'Error: .j2 template references found in libs/'; exit 1; fi
        language: system
        types: [text]