version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6335:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=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
      - PERPLEXITY_API_KEY=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
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
volumes:
  qdrant_data:
