version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6335:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
volumes:
  qdrant_data:
