"""Authentication module for the API."""

from .jwt_handler import jwt_manager, Token, User, TokenData
from .user_management import (
    user_manager,
    UserCreate,
    UserUpdate,
    UserLogin,
    PasswordChange,
)
from .dependencies import (
    get_current_user,
    get_current_active_user,
    require_permission,
    require_any_permission,
    require_role,
    require_any_role,
    require_admin,
    require_developer,
    require_viewer,
    require_read,
    require_write,
    require_delete,
    require_admin_permission,
    require_admin_or_developer,
    require_admin_or_developer_or_viewer,
    require_read_or_write,
    require_write_or_admin,
)
from .routes import router as auth_router

__all__ = [
    "jwt_manager",
    "Token",
    "User",
    "TokenData",
    "user_manager",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "PasswordChange",
    "get_current_user",
    "get_current_active_user",
    "require_permission",
    "require_any_permission",
    "require_role",
    "require_any_role",
    "require_admin",
    "require_developer",
    "require_viewer",
    "require_read",
    "require_write",
    "require_delete",
    "require_admin_permission",
    "require_admin_or_developer",
    "require_admin_or_developer_or_viewer",
    "require_read_or_write",
    "require_write_or_admin",
    "auth_router",
]
