version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: opsvi-qdrant
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=false
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    networks:
      - opsvi-rag
    restart: unless-stopped


volumes:
  qdrant-data:
    driver: local

networks:
  opsvi-rag:
    driver: bridge