site_name: ACCF Research Agent
site_description: Production-ready research agent system with Neo4j GraphRAG and multi-agent orchestration
site_author: ACCF Team
site_url: https://accf-research-agent.readthedocs.io/

# Repository
repo_name: accf-research-agent
repo_url: https://github.com/accf/research-agent
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: user/quick-start.md
    - Installation: user/installation.md
    - Configuration: user/configuration.md
    - First Research Query: user/first-query.md
  - User Guide:
    - Research Workflows: user/research-workflows.md
    - Agent Capabilities: user/agent-capabilities.md
    - API Reference: user/api-reference.md
    - Troubleshooting: user/troubleshooting.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - Development Setup: developer/development-setup.md
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Code Standards: developer/code-standards.md
  - Admin Guide:
    - Deployment: admin/deployment.md
    - Monitoring: admin/monitoring.md
    - Security: admin/security.md
    - Performance Tuning: admin/performance.md
    - Troubleshooting: admin/troubleshooting.md
  - API Documentation:
    - REST API: api/rest-api.md
    - GraphQL API: api/graphql-api.md
    - WebSocket API: api/websocket-api.md

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn

# Copyright
copyright: Copyright &copy; 2025 ACCF Team