# DEFINE AGENT API/PROTOCOL SPECIFICATION OUTPUT TEMPLATE

# This template supports OpenAPI 3.0 YAML, JSON schema, or protocol documentation.
# Use for any agent or service API or protocol specification.

openapi: 3.0.0
info:
  title: "[API/Protocol Title]"
  version: "[Version]"
  description: |
    [Short description of the API, capability, or protocol.]
servers:
  - url: "[https://api.example.com/v1]"
paths:
  /[resource]:
    get:
      summary: "[Summary of GET operation]"
      description: "[Detailed description of GET operation]"
      responses:
        '200':
          description: "[Successful response description]"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/[Resource]'
components:
  schemas:
    [Resource]:
      type: object
      properties:
        id:
          type: string
          description: "[Resource ID]"
        # Add more properties as needed
# For protocol documentation, add a section below:
protocol:
  name: "[Protocol Name]"
  description: |
    [Protocol details, message formats, endpoints, etc.]
  examples:
    - "[Example message or interaction]"
