"""Sphinx configuration for Project Mapper documentation."""

import os
import sys
from pathlib import Path

# Add the project root directory to the path
sys.path.insert(0, str(Path(__file__).parent.parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# Project information
project = "Project Mapper"
copyright = "2023, Project Mapper Team"
author = "Project Mapper Team"

# Full version, including alpha/beta/rc tags
try:
    from proj_mapper.version import __version__
    version = __version__
    release = __version__
except ImportError:
    version = "0.1.0"
    release = "0.1.0"

# General configuration
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "myst_parser",
]

# Add any paths that contain templates here
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The theme to use for HTML and HTML Help pages
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files
html_static_path = ["_static"]

# Theme options
html_theme_options = {
    "collapse_navigation": False,
    "display_version": True,
    "navigation_depth": 3,
}

# Other options
autodoc_member_order = "bysource"
autoclass_content = "both"
add_module_names = False
pygments_style = "sphinx"

# Configure intersphinx
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Set master document
master_doc = "index"

# Enable Markdown support
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Include Python exception in doctest
doctest_default_flags = doctest.NORMALIZE_WHITESPACE | doctest.ELLIPSIS

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True
napoleon_custom_sections = None 