apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-collector:8888
    jsonData:
      timeInterval: 15s
    editable: true